from django.db import models

class UserData(models.Model):
    first_name=models.CharField(max_length=255)
    last_name=models.CharField(max_length=255)
    title=models.CharField(max_length=255)
    gender=models.CharField(max_length=255)
    email=models.CharField(max_length=255)
    city=models.CharField(max_length=255)
    country=models.CharField(max_length=255)
    country_code=models.CharField(max_length=255)
    latitude=models.CharField(max_length=255)
    longitude=models.CharField(max_length=255)
    phone=models.CharField(max_length=255)
    street_address=models.CharField(max_length=255)
    street_name=models.CharField(max_length=255)
    street_number=models.CharField(max_length=255)
    street_suffix=models.CharField(max_length=255)
    time_zone=models.CharField(max_length=255)
    company_name=models.CharField(max_length=255)
    department=models.CharField(max_length=255)
    job_title=models.CharField(max_length=255)
    language=models.CharField(max_length=255)
    university=models.CharField(max_length=255)
    linkedin_skill=models.CharField(max_length=255)
    ip_address=models.CharField(max_length=255)
